# Generated by Django. Initial migration for assets app
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fridge', 'Fridge'), ('oven', 'Oven'), ('washer', 'Washer'), ('dryer', 'Dryer'), ('hvac', 'HVAC'), ('water_heater', 'Water Heater'), ('dishwasher', 'Dishwasher'), ('other', 'Other')], max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('age_years', models.PositiveIntegerField(blank=True, help_text='Age of the appliance in years', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='properties.property')),
            ],
        ),
    ]
