# Generated by Django 5.2.3 on 2025-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('dependant', 'Dependant')], default='primary', max_length=20),
        ),
    ]
